name: barcode_scanner_flutter
description: Barcode Scanner

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_qr_bar_scanner: 3.0.2
  intl: 0.17.0
  sqflite: 2.0.3
  floor: 1.3.0
  bloc: 8.0.3
  flutter_bloc: 8.0.1
  equatable: 2.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  floor_generator: 1.3.0
  build_runner: 2.2.0
  bloc_test: 9.0.3
  mocktail: 0.3.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/images/

